version: '3'
services:
  frontend:
    image: vladbarosan/openapi-platform_frontend
    deploy:
      replicas: 1
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: 40dcf1c8-3f9d-451c-a04e-f596ddf7f091
    ports:
      - '80:5001'
    networks:
      - webnet
  validate:
    image: vladbarosan/openapi-platform_validate
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: 40dcf1c8-3f9d-451c-a04e-f596ddf7f091
    ports:
      - '5002:5002'
    networks:
      - webnet
  validation-worker:
    image: vladbarosan/openapi-platform_validation-worker
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: 40dcf1c8-3f9d-451c-a04e-f596ddf7f091
      AZURE_STORAGE_CONNECTION_STRING: <CONN_STRING>
    ports:
      - '5003:5003'
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - webnet
  visualizer:
    image: 'dockersamples/visualizer:stable'
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet
networks:
  webnet: null
