version: '3'
services:
  frontend:
    image: 'vladbarosan/openapi-platform_frontend:latest'
    deploy:
      replicas: 1
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: <INTRUMENTATION_KEY>
    ports:
      - '80:5001'
    networks:
      - webnet
  validate:
    image: 'vladbarosan/openapi-platform_validate:latest'
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: <INTRUMENTATION_KEY>
    ports:
      - '8080:5002'
    networks:
      - webnet
  validation-worker:
    image: 'vladbarosan/openapi-platform_validation-worker:latest'
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: <INTRUMENTATION_KEY>
      AZURE_STORAGE_CONNECTION_STRING: <CONN_STRING>
    ports:
      - '5003:5003'
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - webnet
  visualizer:
    image: 'dockersamples/visualizer:stable'
    ports:
      - '8081:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet
networks:
  webnet: null
