version: '3.1'
services:
  frontend:
    image: 'vladbarosan/openapi-platform_frontend:latest'
    deploy:
      replicas: 1
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: <>
      VALIDATION_WORKER_URI: 'http://validation-worker:5003'
    secrets:
      - cert_ssl.key
      - cert_sslcrt.pem
    ports:
      - '443:5001'
    networks:
      - webnet
      - proxy
  validate:
    image: 'vladbarosan/openapi-platform_validate:latest'
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: <>
    secrets:
      - cert_ssl.key
      - cert_sslcrt.pem
    ports:
      - '8080:5002'
    networks:
      - webnet
      - proxy
  validation-worker:
    image: 'vladbarosan/openapi-platform_validation-worker:latest'
    deploy:
      replicas: 2
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORKERS: 2
      APPINSIGHTS_INSTRUMENTATIONKEY: <>
      DB_CONNECTION_STRING: <CONN_STRING>
    ports:
      - '5003:5003'
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - webnet
networks:
  webnet: null
  proxy:
    external: true
secrets:
  cert_ssl.key:
    external: true
  cert_sslcrt.pem:
    external: true
