version: '3.1'
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - '80:80'
      - '443:443'
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    secrets:
      - cert_ssl.key
      - cert_sslcrt.pem
    deploy:
      replicas: 2
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - >-
        DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - >-
        DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  proxy:
    external: true
secrets:
  cert_ssl.key:
    external: true
  cert_sslcrt.pem:
    external: true
